### ISSUE TITLE
How to get the final URL?

### ISSUE THREAD

**Issue by stesvis** [xvladxtremal/Faker-LoremFlickr#2]
Is it possible to get the final url of the random image?

For example with `$faker->imageUrl(1200, 850, ['cats', 'dogs'], true)` I get this url: 
http://loremflickr.com/1200/850/cats/?random=1

But if I enter it in the browser it redirects to something like this:
https://loremflickr.com/cache/resized/65535_50273776606_d866f591e7_b_640_480_nofilter.jpg

The problem is that I am generating random images with a `for` loop and they are all the same once rendered:
![image](https://user-images.githubusercontent.com/6062684/96919647-4b288380-1469-11eb-8bb7-d587c4eb1e35.png)

Resulting in:
![image](https://user-images.githubusercontent.com/6062684/96919959-c853f880-1469-11eb-858f-1c187dfdb20a.png)

So, is it possible to return the **actual** resulting URL for each one, so that they can be different images?

**Comment by xvladqt** [comment]
I pushed the fix, now it will be displayed correctly if there are a lot of random images on one page

**Comment by stesvis** [comment]
Awesome thank you!
